### ISSUE TITLE
Enforce code formatting

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/old-tutorbook#248]
# Enforce code formatting

Created: Feb 24, 2020 1:08 PM
Priority: P5
Timeline: Mar 23, 2020
Type: Task 🔨

**Comment by kartikcho** [comment]
How about using an enforced code formatter like [Prettier](https://prettier.io/) ?

**Comment by kartikcho** [comment]
Prettier can be configured to a pre-commit hook using [this](https://www.npmjs.com/package/pretty-quick). Pretty-quick will use rules from .prettierrc files.
This will enforce formatting on commits which seems like the best solution.

This would require settling on a code format pattern. The options guide is [here](https://prettier.io/docs/en/options.html)
Also when this is added to codebase, all the files would need to be processed for formatting.

**Comment by nicholaschiang** [comment]
@kartik918 Thanks for the help!

I'm going to take a look at the options guide, but feel free to fork this repository (off of `develop`) and add that configuration file (with what you think will be best) yourself. Then just make sure to open a PR and we'll get this merged.

I'm looking for three commits in that PR (one to add the config, one to modify the README or add a tutorial (under `tutorials`) and update our `build/docs` by running `make docs`, and finally one to reformat the existing codebase).

**Comment by kartikcho** [comment]
I'll start off with some basic formatting rules, if you find any options to enforce in particular, you can update here.
