### ISSUE TITLE
chore(site): use ES6 imports and exports

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/old-tutorbook#266]
We're using ES6 imports and exports in our `src/app/packages` but I have yet to move over our `src/site/packages` to it (they're still using CommonJS `require` and `module.exports` statements).

We want to replace the `require` function calls with `import` statements and the `module.exports` should be replaced with `export default` statements (in front of class definitions).

**Comment by OrkhanHuseynli** [comment]
@nicholaschiang  I am currently working on this
