### ISSUE TITLE
Goals and reward based system

### ISSUE THREAD

**Issue by ChristopherWong274** [tutorbookapp/old-tutorbook#276]
Hey, I got an interesting idea, we could implement a goal and reward-based system.  A student can set a certain goal and if he reaches it within the time-limited he will receive a reward. The reward maybe some kind of medals that will be added to his profile description.

**Comment by nicholaschiang** [comment]
Moving this [over here](https://github.com/tutorbookapp/covid-tutoring/issues/36).
